---
driver:
  name: ec2
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  aws_ssh_key_id: travis-ci-aws-frank
  security_group_ids: ["sg-2dc50845"]
  region: eu-central-1
  require_chef_omnibus: 12
  instance_type: t2.micro
  tags:
    Name: travis-ci

transport:
  ssh_key: '.travis/travis-ci-aws-frank.pem'
  connection_timeout: 10
  connection_retries: 5

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/postgresql_lwrp_test

platforms:
  - name: ubuntu-14.04
    driver:
     image_id: ami-6bee0004
    transport:
      username: ubuntu
  - name: ubuntu-16.04
    driver:
      image_id: ami-f9e30f96
    transport:
      username: ubuntu

provisioner:
  name: chef_zero

suites:
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.1'
    verifier:
      attributes:
        pg_version: 9.1
  - name: pg-94
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.4'
    verifier:
      attributes:
        pg_version: 9.4
  - name: pg-95
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.5'
    verifier:
      attributes:
        pg_version: 9.5
