---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/postgresql_lwrp_test

platforms:
  - name: debian-8-docker
    driver_config:
      image: debian:8
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
#       For postgreqsl
        - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
        - apt-get install -y locales && locale-gen en_US.UTF-8
#       Netstat for Serverspec
        - apt-get install -y net-tools

  - name: debian-9-docker
    driver_config:
      image: debian:9
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
#       For postgreqsl
        - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
        - apt-get install -y locales && locale-gen en_US.UTF-8
#       Netstat for Serverspec
        - apt-get install -y net-tools
#       gnupg for Chef
        - apt-get install -y gnupg

  - name: ubuntu-14.04-docker
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
#       Netstat for Serverspec
        - apt-get install -y net-tools


  - name: ubuntu-16.04-docker
    driver_config:
      image: ubuntu:16.04
      run_command: '/sbin/init'
      provision_command:
#       For systemd
        - systemctl set-default multi-user.target
#       For postgreqsl
        - apt-get install -y locales && locale-gen en_US.UTF-8
#       Netstat for Serverspec
        - apt-get install -y net-tools

suites:
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.1'
    verifier:
      attributes:
        pg_version: 9.1
    excludes:
      - debian-9-docker

  - name: pg-94
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.4'
    verifier:
      attributes:
        pg_version: 9.4

  - name: pg-96
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '9.6'
    verifier:
      attributes:
        pg_version: 9.6

  - name: pg-10
    run_list:
      - recipe[apt]
      - recipe[pgtest::test]
    attributes:
      pgtest:
        version: '10'
    verifier:
      attributes:
        pg_version: 10
