LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
MethodLength:
  Exclude:
    - 'test/**/spec_helper.rb'
    - 'libraries/helpers.rb'
AbcSize:
  Exclude:
    - 'libraries/helpers.rb'
    - 'test/**/spec_helper.rb'
Documentation:
  Enabled: false
CyclomaticComplexity:
  Exclude:
    - 'libraries/helpers.rb'
