services:
  - docker

language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.1
bundler_args: "--without kitchen_vagrant kitchen_cloud aws"

script: "bundle exec kitchen test ${INSTANCE} --destroy=always"

env:
  global:
  - KITCHEN_YAML=.kitchen.docker.yml
  - secure: Ag8Zn5lQxHrj+Xi79FAKiyq1mJxos+eQe6rL3xrk0aDL10YuAbbYz32jOce1MlIvTsEl4uaVQXQXIJmHjbCqzf5m61FYqRMqVhQ8B+Sh3AYiGe1MYpl9KJSYleyJPqJBDBZ/xfLpDKX7PoUCgXpHm2ZION2YFBHdRx3tN/lejoU=
  - secure: FAO//JQqC+rY3ce19GjA/KWpNskY2nT+8i83WyueHZ20zIc6FMdkWOs+WcEcnfcXDG8GBCqiIG+wF1GajUWirWo+aEIjIguADJhZwuLqD4g6KDmRW9p1MB2b3XDvAbvzze7yy6uG9GcuhiKo+J3S33YugFD59UHGa7hCGeEukAo=
  matrix:
  - INSTANCE=pg-10-debian-9-docker
  - INSTANCE=pg-10-ubuntu-1604-docker
  - INSTANCE=pg-91-debian-8-docker
  - INSTANCE=pg-91-ubuntu-1404-docker
  - INSTANCE=pg-91-ubuntu-1604-docker
  - INSTANCE=pg-94-ubuntu-1404-docker
  - INSTANCE=pg-94-ubuntu-1604-docker
  - INSTANCE=pg-96-ubuntu-1404-docker
  - INSTANCE=pg-96-ubuntu-1604-docker

jobs:
  include:
    - stage: lint
      script:
        - bundle exec cookstyle --version
        - bundle exec cookstyle
        - bundle exec foodcritic --version
        - bundle exec foodcritic --contex  --epic-fail any --tags ~chef13 .

    - stage: deploy
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_b45d6f20bf91_key -iv $encrypted_b45d6f20bf91_iv
          -in .travis/secret_keys.tar.enc -out .travis/secret_keys.tar -d
        - tar xf .travis/secret_keys.tar -C .travis
        - mv .travis/travis_rsa ~/.ssh/id_rsa
      deploy:
        edge: true
        provider: chef-supermarket
        user_id: express42
        client_key: ".travis/express42.pem"
        cookbook_category: Databases
        skip_cleanup: true
        on:
          tags: true

notifications:
  slack:
    secure: M7REbNB5Wf6eMBxQijnquWw4KlBbrw5zLM6fWqB1CjA3IF7DbYFUgvBTeUAxTFE9P2KEahYydPRkhzDtQ49PpE31g93yfy1yqQ/1rBHuzmZztR1hpwzYAhzGg4cak/47LQPaHx6Y9Pa83N8BPwpE4t9936wB3gXBlQERQdGdmoE=
